export const CONFIG = {
  NAME: "zulfaa",
  TEXTS: [
    "HAPPY BIRTHDAY",
    "SEHAT SELALU",
    "SEMUA CITA2NYA",
    "TERCAPAI",
    "JADI,ANAK SOLEHAH",
    "YG,SAYANG ORTU",
    "DAN BANYAK UANGNYA",
    "AMINNN"
  ],
  FIREWORK_DURATION: 350,
  HEART_SPEED: 0.02,
  PARTICLE_LIMIT: 6000
};
